# Generated by Django 5.2.15 on 2026-07-23 02:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Personaje',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=200)),
                ('altura', models.CharField(blank=True, default='', max_length=50)),
                ('peso', models.CharField(blank=True, default='', max_length=50)),
                ('personalidad', models.TextField(blank=True, default='')),
                ('historia', models.TextField(blank=True, default='')),
                ('beyblade', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='personajes', to='api.beyblade')),
            ],
        ),
    ]
