# Generated by Django 5.2.15 on 2026-07-23 03:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_personaje'),
    ]

    operations = [
        migrations.AddField(
            model_name='personaje',
            name='foto',
            field=models.ImageField(blank=True, null=True, upload_to='personajes/'),
        ),
    ]
