# Generated by Django 5.2.15 on 2026-07-23 03:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_personaje_foto'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='personaje',
            name='beyblade',
        ),
        migrations.AddField(
            model_name='personaje',
            name='beyblades',
            field=models.ManyToManyField(blank=True, related_name='personajes', to='api.beyblade'),
        ),
    ]
